### ISSUE TITLE
Usage examples in readme?

### ISSUE THREAD

**Issue by bbuchalter** [trevrosen/Redis-Cacheable#1]
Sorry to bother, but I believe you've got some code here that would help me, however I'm having trouble getting started.  Could you provide some usage examples?  By reading the source, it seems I include the Redis-Cacheable module in my class and then call rc_write! to dump a class instance into redis.  Right?

What seem strange is the retrieval of the object.  In my case, I've got this object that's quite expensive to load.  I want to use your library to cache the object in redis.  However, it seems I need to instantiate the object with the correct key_method attribute in order to call rc_read to retrieve the object. Seems awkward. 

Perhaps a few usage examples in the README would help?  Thanks!

**Comment by trevrosen** [comment]
Hey man,
Sorry it's taken me a bit to get back to you.  This is actually a kind of demo gem that I made for a talk I was giving at Austin.rb a few months back.  There are many, many things that could make this better.  One reason why I've never put it in RubyGems… :-\  

That being said, it should definitely be usable for you.  You're essentially correct in how it works -- I'm not sure how you'd find something in Redis w/out a key, so there's definitely some necessary data in that sense.  There's significant info on how to use it in the goofy little demo project I made for it:

https://github.com/trevrosen/Rufus-Pig-Foot-Emporium/

More specifically, the Composite class:

https://github.com/trevrosen/Rufus-Pig-Foot-Emporium/blob/master/lib/dashboard/composite.rb

Hope that helps -- good luck!  Let me know how it goes.

-TR
